### ISSUE TITLE
Plugin überschreibt lokale Konfiguration

### ISSUE THREAD

**Issue by katgirl** [ErdmannFreunde/optimist-theme-bundle#10]
In https://github.com/erdmannfreunde/optimist-theme-bundle/blob/master/src/ContaoManager/Plugin.php#L21
wird die Config überschrieben.

see: https://github.com/contao/contao/issues/3357

**Comment by denniserdmann** [comment]
Es ist eigentlich kein Bug, sondern ein Feature. Denn Folder-URL wird benötigt damit die Unterseite der Demo funktionieren. Aber ich werde sehen, was wir tun können.

**Comment by katgirl** [comment]
Entweder müsste der Manager dann vorher das Config-Objekt lesen und mitgeben oder man müsste sich selbst das Objekt holen und dann nur den Wert verändern.

**Comment by fritzmg** [comment]
> Es ist eigentlich kein Bug, sondern ein Feature. Denn Folder-URL wird benötigt damit die Unterseite der Demo funktionieren. Aber ich werde sehen, was wir tun können.

The feature is fine, however you are overwriting any existing configuration with your plugin, making it impossible to set anything else via `contao.localconfig`. You need to merge the configuration instead of overwriting it. So instead of

```php
$extensionConfigs[] = ['localconfig' => ['folderUrl' => true]];
```` 

you need to use

```php
$extensionConfigs['localconfig'] = array_merge($extensionConfigs['localconfig'] ?? [], ['folderUrl' => true]);
```

for example.

**Comment by katgirl** [comment]
you meen

```php
foreach($extensionConfigs as $id=>$value) {
  $extensionConfigs[$id]['localconfig'] = array_merge($extensionConfigs[$id]['localconfig'] ?? [], ['folderUrl' => true]);
}
```
you need a new array

**Comment by denniserdmann** [comment]
@katgirl fixed in https://github.com/erdmannfreunde/optimist-theme-bundle/tree/hotfix/1.1.10

Can you check it in your installation?

**Comment by katgirl** [comment]
> Can you check it in your installation?

It fits, thank you very much

**Comment by denniserdmann** [comment]
fixed in 1.1.10
