### ISSUE TITLE
Dateien werden nicht kopiert / Datenbank-Import nicht möglich

### ISSUE THREAD

**Issue by denniserdmann** [ErdmannFreunde/optimist-theme-bundle#12]
Aufgrund der neuen Composer Version und `allow-plugins` können die Dateien aus dem ZIP-Archiv nicht mehr in `files` und `templates` kopiert werden.

**Comment by denniserdmann** [comment]
~~**Lösung:** die composer.json muss um folgende Zeilen ergänzt werden (vor der letzten schließenden Klammer):~~


```
entfernt, da mit Contao Manager 1.5.1 erledigt
```

**Erklärung**: Damit erlaubst du Composer / dem Contao Manager, das Optimist Code ausführen kann, der die entsprechenden Dateien aus dem Archiv in `files` und `templates` kopiert. 

`allow-plugins` wurde als neue Sicherheitsfunktion eingeführt und soll dem Nutzer mehr Kontrolle über verwendete Composer-Plugins geben. In Composer wird der Nutzer über einen Dialog um Einverständnis gebeten, im CM wird diese Abfrage momentan unterdrückt. 

~~Wir prüfen zurzeit, welche Lösungen und Alternativen es gibt, um dir die Theme-Installation wieder so einfach wie möglich zu machen.~~ Die Lösung wurde in den Contao Manager integriert.

**Comment by mgeha** [comment]
Bei mir funktioniert das Kopieren der Dateien trotz dem aktuellen master und composer 2.2.8 nicht.
Reicht es die Dateien von vendor/erdmannfreunde/optimist-theme-bundle/skeleton/ in die entsprechenden Ordner in der Contao Installation zu kopieren?

**Comment by denniserdmann** [comment]
> Bei mir funktioniert das Kopieren der Dateien trotz dem aktuellen master und composer 2.2.8 nicht.
 
Ohne Log ist es schwer zu beurteilen woran es liegen könnte. Hast du die Ergänzung in der composer.json wieder entfernt?

> Reicht es die Dateien von vendor/erdmannfreunde/optimist-theme-bundle/skeleton/ in die entsprechenden Ordner in der Contao Installation zu kopieren?

Ja, grundsätzlich ist das die Hauptaufgabe des Contao Managers, wenn man das ZIP-Archiv hochlädt. Zusätzlich wird „folderURL“ noch in Contao aktiviert, damit die URLs aus der Demo funktionieren und es werden die Erweiterungen, die in der composer.json aufgeführt sind, installiert. 

Du solltest also prüfen, ob abgesehen vom Dateien kopieren die anderen Schritte durchgeführt wurden.

**Comment by mgeha** [comment]
Hi Dennis. Ich habe die Installation mit dem aktuellen Contao Manager gemacht, war wohl etwas missverständlich ausgedrückt. Ich wollte nur sagen das composer in aktueller Version vorlag. Der Manager quitiert das Installieren ohne Fehlermeldung. Das Log sah unauffällig aus. Ich versuche es die Tage nochmal in einer Testinstallation nachzustellen und würde dann das Log übermitteln.

Ansonsten habe ich durch Kopieren das Theme zum laufen bekommen. Thx für die flotte Hilfe.
