### ISSUE TITLE
Wie updaten

### ISSUE THREAD

**Issue by kroerig** [ErdmannFreunde/optimist-theme-bundle#13]
Hallo,

wie mache ich denn ein Update des Themes auf die aktuelle Version. z.B. um im Anschluss Contao 4.9 auf 4.13 zu heben oder auch einfach um Fehler auszubügeln?

Ich habe über den Contao Manager einfach das neue Zip installiert, jetzt steht da auch Version 1.3.0 (angefangen haben ich mit 1.1.5), aber an den Dateien hat sich nichts geändert.

Soll/ Muss ich die Template und SCSS  zu Fuß austauschen und ggf. eigene Anpassungen einmergen?

**Comment by denniserdmann** [comment]
> Soll/ Muss ich die Template und SCSS zu Fuß austauschen und ggf. eigene Anpassungen einmergen?

Ja. 

Sobald es den Ordner files/theme gibt, werden die Dateien nicht mehr aus dem Theme kopiert (sondern nur noch, was in der composer.json steht). Sonst müsstest du auch damit rechnen, dass wir SCSS- oder Template-Anpassungen, die du gemacht hast, überschreiben würden.
