### ISSUE TITLE
Update 4.12.5 auf 4.13.* schlägt fehl

### ISSUE THREAD

**Issue by berecont** [ErdmannFreunde/optimist-theme-bundle#14]
Testinstallation 4.12.5
Der Versuch auf ^4.13 via Contao Manager hochzuheben bricht leider ab (dry run).
```
composer require contao/manager-bundle=4.13.* erdmannfreunde/optimist-theme-bundle=1.3.0 contao/news-bundle=4.13.* contao/calendar-bundle=4.13.* contao/faq-bundle=4.13.* contao/comments-bundle=4.13.* contao/newsletter-bundle=4.13.* contao/listing-bundle=4.13.*
$ /usr/local/php74/bin/php -q -dmax_execution_time=0 -dmemory_limit=-1 -dallow_url_fopen=1 -ddisable_functions= -ddate.timezone=Europe/Berlin /var/www/vhosts/mein.hosting.netcup.net/httpdocs/meinprojekt/web/contao-manager.phar.php composer require contao/manager-bundle=4.13.* erdmannfreunde/optimist-theme-bundle=1.3.0 contao/news-bundle=4.13.* contao/calendar-bundle=4.13.* contao/faq-bundle=4.13.* contao/comments-bundle=4.13.* contao/newsletter-bundle=4.13.* contao/listing-bundle=4.13.* --no-update --no-scripts --prefer-stable --sort-packages --no-ansi --no-interaction
In InputBag.php line 30:
                                                                               
  Declaration of Symfony\Component\HttpFoundation\InputBag::get(string $key,   
  $default = NULL) should be compatible with Symfony\Component\HttpFoundation  
  \ParameterBag::get($key, $default = NULL)                                    
                                                                               
require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>...]
# Process terminated with exit code 1
# Result: General error
```
letzte Version zip Datei 1.3.0 wurde via CM hochgeladen, alle aktualisieren und der Update Versuch gestartet.
Liegt das Problem im Optimist Theme?

**Comment by denniserdmann** [comment]
Sieht für mich nicht so aus.

Hast du evtl. eigene Erweiterungen im Einsatz, die ` Symfony\Component\HttpFoundation` verwenden?

**Comment by berecont** [comment]
Nein, eigene Erweiterungen sind nicht im Einsatz.
Aber ich konnte nun erfolgreich auf 4.13.1 hochheben » mit Workaround und damit auch eine "Bestätigung", dass Optimist der Fehlerverursacher sein müsste:

- mit den Umwegen der Fehlermeldungen, Vendor-Ordner löschen, div. Abbrüchen, Abgesicherter Modus, etc. ...
- Optimistpaket entfernen
- Update auf 4.13.*
- neues, aktuelles Optimistpaket installieren
- Datenbank aktualisiert 
- läuft

Es gab auch bereits auf Slack einen thread dazu. Ich bin wohl in den gleichen Fehler gelaufen und konnte ihn dann mit dem beschriebenen workaround beheben.
[Slack](https://contao.slack.com/archives/CK4J0KNDB/p1647442425802799?thread_ts=1647435994.437139&cid=CK4J0KNDB)

**Comment by denniserdmann** [comment]
Danke für den Hinweis. Ich werde bei Gelegenheit mal schauen, ob ich das Problem nachgestellt bekomme. 

Zum besseren Verständnis: 
Hast du bei deinem 1. Versuch Contao 4.13 und OPTIMIST 1.3 gleichzeitig aktualisiert? Oder erst das eine und dann das andere? So kann ich den Fehler beim Testen eingrenzen.

**Comment by berecont** [comment]
Ja, im 1.Versuch wurde 1.3.0 als *.zip hochgeladen, alles markiert, auf ^4.13.* abgeändert und versucht zu aktualisieren (Testlauf)... Fehlermeldung siehe oben
