### ISSUE TITLE
Installation unter Contao 5.02 nicht möglich

### ISSUE THREAD

**Issue by AgentCT** [ErdmannFreunde/optimist-theme-bundle#16]
Hallo,

ich wollte gerade euer schönes Theme unter Contao 5.02 instllieren. Leider bricht die Installtion mit folgender Meldung ab:

`Installiere hochgeladene Paketeoptimist-theme-bundle-master.zip
composer require erdmannfreunde/optimist-theme-bundle=1.4.0
composer update erdmannfreunde/optimist-theme-bundle contao/conflicts --no-install

> Resolving dependencies using Composer Cloud v3.5.0
!!! Current server is sponsored by: terminal42 gmbh !!!
[6.5MiB/0.18s] Loading composer repositories with package information
[6.9MiB/0.26s] Info from https://repo.packagist.org: #StandWithUkraine
[65.0MiB/7.80s] Updating dependencies
[94.3MiB/8.12s] Your requirements could not be resolved to an installable set of packages.
[94.3MiB/8.12s] 
  Problem 1
    - Root composer.json requires erdmannfreunde/optimist-theme-bundle 1.4.0 -> satisfiable by erdmannfreunde/optimist-theme-bundle[1.4.0].
    - erdmannfreunde/optimist-theme-bundle 1.4.0 requires contao/manager-bundle ^4.9 -> found contao/manager-bundle[4.9.0, ..., 4.13.10] but it conflicts with your root composer.json require (5.0.*).
[94.3MiB/8.12s] <warning>Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.</warning>
[35.3MiB/8.16s] Memory usage: 35.32MB (peak: 173.57MB), time: 8.18s.
[35.3MiB/8.17s] Finished Composer Cloud resolving. 
Cloud Job ID Hmvq2zeymVLY4jDLRbRaTLvhedDMsCk69KDltXAcyfxA8ecubrxvY828cz7hmZLfoHhD4RZ3FBOpiYh3tAY3Y1qvLknSKIjs failed
vendor/bin/contao-console contao:maintenance-mode enable
composer install
vendor/bin/contao-console contao:maintenance-mode disable
Entferne hochgeladene Dateienoptimist-theme-bundle-master.zip`

Ich hoffe ihr findet eine Lösung, zurzeit kann man es leider nicht installieren.

Vielen Dank
Stefan

**Comment by denniserdmann** [comment]
Moin Stefan,

das ist richtig. OPTIMIST funktioniert noch nicht mit Contao 5. Du kannst stattdessen die aktuelle LTS 4.13 verwenden.

**Comment by AgentCT** [comment]
Okay vielen Dank dann werde ich es mit der 4.13 versuchen.

**Comment by kroerig** [comment]
gibt es schon einen (Zeit-) Plan das tolle Theme für Contoa 5.3 anzupassen.
Die 4.13 hat zwar noch fast 2 Jahre Support. Aber so langsam fallen die Erweiterungen hinten runter.

**Comment by denniserdmann** [comment]
Ja, den gibt es. 

Aus unserem [Newsletter](https://erdmann-freunde.de/wissen/newsletter):

>Wird es das [OPTIMIST-Theme](https://erdmann-freunde.de/contao-themes/optimist) auch für Contao 5 geben?
> …
> Ja, ich werde OPTIMIST auch für Contao 5 optimieren. Aber erst, nachdem ich alle anderen Contao Themes (mit denen wir Geld verdienen) aktualisiert habe.
>
> Denn der Schritt von Contao 4 auf 5 ist gar nicht so klein, wie er scheint. Dadurch, dass die Inhaltselemente neue Klassen-Namen bekommen haben (z. B. content-text statt ce_text) muss ich einmal durch alle Anweisungen gehen und so anpassen, dass die Darstellung wieder passt.
>
> Für [SIRIUS](https://erdmann-freunde.de/contao-themes/sirius) und [SOLO](https://erdmann-freunde.de/contao-themes/solo) habe ich die Arbeit schon hinter mir, bei LASR bin ich gerade dabei. Momentan schätze ich, dass OPTIMIST für Contao 5 im Herbst erscheint.

**Comment by kikmedia** [comment]
Was braucht es denn zur Kompatibilität? Kann ich irgendwie unterstützen?

**Comment by denniserdmann** [comment]
Ich werde nächste Woche mit der neuen Version beginnen. 

@kikmedia ich kann dich gerne kontaktieren, wenn es darum geht, die neue Version zu testen.

**Comment by denniserdmann** [comment]
Wer beim Testen der neuen Version helfen möchte:
https://erdmann-freunde.de/newsletter/details/ich-brauche-deine-hilfe

cc @kikmedia

**Comment by kikmedia** [comment]
Check.

**Comment by denniserdmann** [comment]
Mit Version 3 ist nun auch die Installation unter Contao 5 möglich. Neu ist, dass das Theme nun ein „contao-theme“ ist und dadurch direkt bei der Installation von Contao über den Manager installiert werden kann: https://erdmann-freunde.de/contao-themes/optimist/installation

**Comment by kroerig** [comment]
Super.
Wie sieht es denn mit einen (Inplace) Update aus? Geht das? Was kann/ muss man übertragen oder neu machen?

**Comment by denniserdmann** [comment]
> Super. Wie sieht es denn mit einen (Inplace) Update aus? Geht das? Was kann/ muss man übertragen oder neu machen?

schau mal hier: https://github.com/erdmannfreunde/optimist-theme-bundle/compare/2.x...3.x?diff=split&w=1

Es sieht nach viel aus, aber wenn man die Leerzeichen, Umbrüche und geänderten Hex-Werte ausklammert, dann hält sich der Aufwand in Grenzen.

**Comment by kroerig** [comment]
nur mal kurz überflogen:
Die Namensänderungen bei den Klassen für einzelne Inhalte können mir egal sein. Die Dateien werden einfach ersetzt. Alles was ich anpassen muss steht in der `_variables.scss`, die muss ich mich vorher sichern. Aber hier sehe ich außer ein paar Zeilenumbrüchen für die Lesbarkeit keinen Unterschied.

Die Demo-Inhalte will ich ja nicht installieren, habe ja schon eigene.

Habe ich irgendwas übersehen?

**Comment by denniserdmann** [comment]
ich glaube, es sind ein paar Variablen dazu gekommen, aber abgesehen davon sollte es das für dich gewesen sein.

**Comment by kroerig** [comment]
Das passt. Jetzt muss ich nur noch herausfinden, wie das Upgrade inplace funktioniert.
Bisher habe ich diesen Block in der composer.json:

```
    "repositories": {
        "erdmannfreunde/optimist-theme-bundle": {
            "type": "artifact",
            "url": "contao-manager/packages/"
        }
    },
```

Ich vermute mal den muss ich rausnehmen, damit Composer sich das Bundle vom Server zieht oder?
