### ISSUE TITLE
Fehler nach Update auf Version 2.0.2

### ISSUE THREAD

**Issue by kroerig** [ErdmannFreunde/optimist-theme-bundle#17]
Ich habe, wie beschrieben, das Bundle über den Manager installiert und dann manuell, die SCSS-Dateien - bis auf die _variables.scss - ausgetauscht.
Bekomme aber jetzt nur noch eine Fehlermeldung "Es ist ein Fehler aufgetreten" beim Seitenaufruf und im Log steht:
`[2023-02-05T21:12:26.058226+01:00] request.CRITICAL: Uncaught PHP Exception ScssPhp\ScssPhp\Exception\CompilerException: "`../../nutshell/scss/variables` file not found for @import: _variables.scss on line 12, at column 1 Call Stack: #0 import _variables.scss default.scss on line 14" at /var/www/web0/html/demo/vendor/scssphp/scssphp/src/Compiler.php line 6102 {"exception":"[object] (ScssPhp\\ScssPhp\\Exception\\CompilerException(code: 0): `../../nutshell/scss/variables` file not found for @import: _variables.scss on line 12, at column 1\nCall Stack:\n#0 import _variables.scss default.scss on line 14 at /var/www/web0/html/demo/vendor/scssphp/scssphp/src/Compiler.php:6102)"} []`

Habe auch schon mehrfach alle Caches geleert, die Dateiverwaltung neu synchronisiert. Hilft alles nichts.

**Comment by kroerig** [comment]
Ok. Fehler 1 gefunden:
In der _variables.scss hat sich in Zeile 12 der Pfad geändert.

Aber es fehlen noch Formatierungen. Wo hat sich noch was geändert?

**Comment by kroerig** [comment]
mir scheint, ich muss die _variables.scss neu aufbauen.

**Comment by denniserdmann** [comment]
Moin!

Version 1 und 2 sind nicht ohne größere Anpassungen kompatibel. Eine Übersicht über alle Änderungen findest du hier: https://github.com/erdmannfreunde/optimist-theme-bundle/compare/1.x...2.x

Ein Überblick:

- Pfade zum Nutshell Framework anpassen
- Variablen-Bezeichnungen anpassen
- neue Dateien _article.scss und _config.scss erstellen

Ich empfehle, bestehende 1.X Projekte nicht auf 2.X zu aktualisieren.

**Comment by kroerig** [comment]
> Ich empfehle, bestehende 1.X Projekte nicht auf 2.X zu aktualisieren.

Jetzt steht ja bald die 5.3 LTS an. Und ohne Update auf die 2.x wird das vermutlich nichts werden, oder?

**Comment by denniserdmann** [comment]
Es ist richtig, dass nur die Version 2 mit Contao 5 kompatibel sein wird. 
Aber auch bei Version 2 wird es noch eine Weile dauern, bis OPTIMIST „out of the box“ mit Contao 5 funktioniert.

Du könntest also jetzt schon in Ruhe dein Projekt auf OPTIMIST 2 aktualisieren, dann ist das Update auf Contao 5 deutlich einfacher.

**Comment by kroerig** [comment]
Hast du eine Anleitung?

Ich kann mich erinnern, dass ich bei der letzten Aktion ordentlich suchen musste, bis ich alle Fallstricke überwunden hatte.

**Comment by denniserdmann** [comment]
Es gibt keine Anleitung für ein Update von OPTIMIST 1 auf 2 (sie wird auch nicht kommen). Folgendes könntest du aber machen: 

- die jetzigen `theme`-Ordner in z. B. `theme-v1` innerhalb von files und templates umbenennen und in Contao im Theme und Seitenlayout die geänderten Ordner berücksichtigen 
- OPTIMIST 1 über den Contao Manager entfernen
- OPTIMIST 2 über den Contao Manager installieren
- Die Theme-Anpassungen, die du in V1 gemacht hast (Farben, Schriften etc.), in V2 ebenfalls vornehmen

Ich würde das in einer Kopie der LIVE-Installation machen, damit die Website weiterhin erreichbar ist.

**Comment by kroerig** [comment]
> Ich würde das in einer Kopie der LIVE-Installation machen, damit die Website weiterhin erreichbar ist.

Das wäre in dem sogar egal. Bis Ende März bleibe ich bei dem 1.3er Projekt auf jeden Fall noch auf der Version. Dann schläft die Seite wieder für ein Jahr und ich habe alle Zeit der Welt.
