### ISSUE TITLE
Verhalten der mobilen Navigation bei Änderung des Viewports

### ISSUE THREAD

**Issue by rflx** [ErdmannFreunde/optimist-theme-bundle#2]
Beim toggeln der Navigation fehlt ein `$(window).resize()` oder ähnliches Verhalten wenn der Viewport vergrössert wird bei aktiver Navigation. 

Beispiel: verlassen des mobilen Viewports bei aktiver Navigation.

**Comment by denniserdmann** [comment]
Vielen Dank für den Hinweis. Wird in der nächsten Version behoben.

**Comment by denniserdmann** [comment]
fixed in [1.0.3](https://github.com/ErdmannFreunde/optimist-theme-bundle/tree/1.0.3)
