### ISSUE TITLE
Abhängigkeit Ping-Bundle

### ISSUE THREAD

**Issue by katgirl** [ErdmannFreunde/optimist-theme-bundle#20]
Ich finde es Datenschutzrechlich schwierig in  der heutigen Zeit in ein Theme ein Ping einzubauen, der nach Hause die Contao-Version und die URL übermittelt.
Wenn dann müsste das zumindest klar aus der Readme hervorgehen.

**Comment by denniserdmann** [comment]
Ich werde die Readme entsprechend ergänzen (auf unserer Website haben wir den Hinweis seit August in der FAQ drin: https://erdmann-freunde.de/contao-themes/detail/wie-wird-geprueft-ob-ich-das-theme-fuer-eine-installation-einsetze)

**Comment by denniserdmann** [comment]
Ich habe einen Hinweis ergänzt.
