### ISSUE TITLE
Browser Support Popup bei Safari Mobile

### ISSUE THREAD

**Issue by rflx** [ErdmannFreunde/optimist-theme-bundle#3]
Ich habe ein komisches Verhalten festgestellt bei Safari Mobile. Dort wird manchmal das DIV "Browser Support" ausgegeben und manchmal nicht. Woran könnte das liegen? Be `fe_page.html5` ist diese Bedingung drin:

```
<?php
  $this->import('Environment');
  $ua = $this->Environment->agent;
?>
<?php if ($ua->browser == 'ie' || ($ua->browser == 'edge' && $ua->version <= '17')): ?>
…
<?php endif; ?>

**Comment by denniserdmann** [comment]
Das ist merkwürdig und mir bisher nicht passiert. Die Bedingung bezieht sich auf den Internet Explorer bzw. MS Edge kleiner/gleich Version 17. Wenn du auf den Hinweis verzichten kannst, kannst du die `fe_page.html5` auch einfach löschen.

Aber vielleicht kannst du das Problem weiter eingrenzen?

**Comment by rflx** [comment]
Ja, momentan verzichte ich auf den Hinweis. Zuerst dachte ich es sei ein Caching-Problem aber nach mehrmaliges Löschen von Browser- und Servercache konnte ich die Anzeige wieder reproduzieren. Komisch finde ich, dass es auf Safari trotzdem angezeigt wird, obwohl es nicht in der Bedingung drin ist.

**Comment by rabauss** [comment]
Witzigerweise hatten wir heute beim Live-Gang eines Projekts auch ähnlichen Fall.
Dieser Hinweis ist gut gedacht, aber der Browser sollte nicht serverseitig ausgewertet werden, v.a. nicht bei aktiviertem Contao-Cache.

Denn wenn dann ein Besucher mit altem Browser die Seite besucht, dann wird der Hinweis ebenfalls im Cache gespeichert. 
Daraufhin bekommen auch neuere Browser den Hinweis aus dem Cache angezeigt!

Vermutlich sollte man den Hinweis lieber immer rendern, aber nur per CSS einblenden oder vielleicht nur ein CSS-Pseudoelement.
```
@media all and (-ms-high-contrast: none), (-ms-high-contrast: active) {
     /* IE10+ CSS styles go here */
}
```

Oder liegt hier doch ein Contao 4.9.4 Problem vor?

**Comment by denniserdmann** [comment]
Guter Hinweis. Ich denke, ich werde mich mal nach einer JS-Lösung umsehen. z.B. diese hier: https://codepen.io/gapcode/pen/vEJNZN

**Comment by rabauss** [comment]
Mit dem Script + Jquery würde die Lösung folgendermaßen aussehen, um das gleiche Verhalten wie über `fe_page.html5` zu erreichen. Dann kann man auch wieder den Cache aktivieren! Ich hatte schon geahnt, dass uns das beim Live-Gang mit aktiviertem Cache ein paar Probleme bereiten wird ;-)

```javascript
$(document).ready(function () {
    var version = detectIE();
    if (version !== false && version <= 17) {
        var browser_support =
            '<div class="browser-support heading--5">' +
                '<div class="inside">' +
                  '<h2>Ihr Webbrowser ist veraltet.</h2>' +
                  '<p>Aktualisieren Sie Ihren Browser um den bestmöglichen Komfort der Website zu genießen.</p>' +
                '</div>' +
            '</div>';
        $('body').prepend(browser_support);
    }
});
```

**Comment by denniserdmann** [comment]
fixed in [1.0.3](https://github.com/ErdmannFreunde/optimist-theme-bundle/tree/1.0.3)
