### ISSUE TITLE
Seite ist nicht skalierbar solange ein Slider benutzt wird (RockSolid Slider und/oder Slick)

### ISSUE THREAD

**Issue by yarekpietrasina** [ErdmannFreunde/optimist-theme-bundle#5]
Mit einem Schieber funktioniert leider OPTIMIST nicht 100%ig korrekt. 

Ich habe folgende Lösungen ausprobiert:

- RockSolid Slider umsetzen

- Slick von heimrichhannot umsetzen

- Mobile Menü ausblenden

Leider immer wieder kommt der Fehler vor: https://www.loom.com/share/f640df1d198048e1b8ebbf0d5c64426b

Ähnliche Warnung gibt's schon hier: https://github.com/ErdmannFreunde/optimist-theme-bundle/issues/2

**Comment by denniserdmann** [comment]
Moin @JarekYaro,
ich kann den Fehler bestätigen, er tritt auch beim Contao Slider auf. Kannst du mal folgendes testen?

```
[id='container'] {
  overflow: hidden;
}
```

Dadurch wird im Contao Slider das Problem behoben. Ich habe die anderen Slider noch nicht getestet.

**Comment by yarekpietrasina** [comment]
Hallo Dennis,

ja. Es scheint richtige Lösung zu sein. Danke dir für die schnelle Antwort. 

👍

**Comment by yarekpietrasina** [comment]
Bitte berücksichtigen, dass `overflow: hidden;` `position: sticky; ` tötet (wird z.B. beim Formular in News-Reader benutzt) 

Um das zu vermeiden, soll man `overflow: hidden;` in das parent-div des Sliders einfügen (statt in #container)

**Comment by denniserdmann** [comment]
@JarekYaro Ich habe das Problem für den Contao Slider damit beheben können, dass ich ihm die Anweisung `display: grid` gegeben habe. Dadurch hat das Script die Breite wieder korrekt berechnen können (`overflow: hidden` hingegen hat beim Contao Slider nicht gereicht).

**Comment by alwinvollmer** [comment]
@JarekYaro, @denniserdmann das eigentliche Problem liegt bei [id="wrapper"]. Dort wird display:grid verwendet 

`display: grid;
grid-template-rows: min-content auto min-content;`

um header, content und footer auszurichten. Allerdings werden an der Stelle nur die rows deklariert und die default width eines grid elements ist "auto" was zu beschriebenem Problem führt.

tldr: `grid-template-columns: 100%;` 
man deklariert eine Spalte mit 100% Breite, das löst das Problem.

**Comment by denniserdmann** [comment]
@alwinvollmer Vielen Dank für den Hinweis. Da wäre ich im Leben nicht drauf gekommen.
