### ISSUE TITLE
Installation unter Contao 4.11 mit PHP 8 bricht ab

### ISSUE THREAD

**Issue by kroerig** [ErdmannFreunde/optimist-theme-bundle#6]
Hallo,

ich wollte gerade das Thema auf einer frischen Contao 4.11 (Core) installieren. Composer bricht aber ab:

```
- Artefakt für erdmannfreunde/optimist-theme-bundle (Version 1.1.5) [nach packages/erdmannfreunde__optimist-theme-bundle__1.1.5.0__57572f70.zip] installiert

$ /opt/php-8.0/bin/php -q -dmax_execution_time=0 -dmemory_limit=-1 -dallow_url_fopen=1 -ddisable_functions= -ddate.timezone=Europe/Berlin /var/www/web0/html/web/contao-manager.phar.php composer require erdmannfreunde/optimist-theme-bundle=1.1.5 --no-update --no-scripts --prefer-stable --sort-packages --no-ansi --no-interaction


In InitCommand.php line 749:
                                                                               
  Package erdmannfreunde/optimist-theme-bundle has a PHP requirement incompat  
  ible with your PHP version, PHP extensions and Composer version              
                                                                               

require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--no-scripts] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [...]


 Process terminated with exit code 1
 Result: General error
```

**Comment by kroerig** [comment]
Nachtrag: mit PHP 7.4 läuft die Installation durch.

**Comment by denniserdmann** [comment]
Das kann gut sein. Wir bieten momentan noch keinen Support für PHP 8 an, da Contao PHP 8 auch erst seit letztem Donnerstag von umfänglich unterstützt. Genauso haben wir OPTIMIST noch nicht für Contao 4.11 aktualisiert. 

Wir werden erst unsere kostenpflichtigen Themes aktualisieren, dann folgt OPTIMIST.

**Comment by kroerig** [comment]
OK, dann gehe auf die 4.10 zurück. Kann ich auch mit leben. Wollte es nur hier melden, damit andere nicht auch in den Fehler laufen.

**Comment by kroerig** [comment]
Hm, 4.10 will auch nicht, obwohl 410 als Template angeboten wird:

`
Der Import konnte nicht abgeschlossen werden! Ist die Datenbank aktuell und die Template-Datei kompatibel mit Ihrer Contao-Version?
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'featured' in 'field list'
`

**Comment by denniserdmann** [comment]
Ich kann den Fehler mit 4.10 bei mir nicht nachvollziehen. Die Installation mit 4.10.7 funktionierte und der Import ebenfalls:

![image](https://user-images.githubusercontent.com/3773697/108761256-ea13d800-754e-11eb-8bd9-70c52bac5187.png)

**Comment by katgirl** [comment]
siehe https://github.com/ErdmannFreunde/optimist-theme-bundle/pull/9 
Contao 4.10 < PHP 8
Contao 4.11 geht auch PHP 8 jedoch viele Erweiterungen nicht
Optimist läuft aber ohne Probleme durch

**Comment by denniserdmann** [comment]
Wir werden das Thema PHP 8 nach dem OTC in Angriff nehmen. 

Da OPTIMIST von Erweiterungen wie dem Grid-Bundle abhängig ist, bringt es nichts, wenn OPTIMIST sich zwar installieren, aber nicht verwenden lässt 😉 Deswegen werden wir erst unsere Extensions für PHP 8 aktualisieren, dann die Themes.

**Comment by katgirl** [comment]
Kleine Rückmeldung
- erdmannfreunde/contao-grid-bundle
- erdmannfreunde/euf_contact
- erdmannfreunde/euf_hero
- erdmannfreunde/euf_nutshell
- erdmannfreunde/portfoliobundle
- erdmannfreunde/theme-toolbox

sowie Optimist und Sirius laufen bei mir bereits auf PHP 8 ohne Probleme. Nur mit der Installation via ansible unter PHP 8 hängt es an Optimist, da hier PHP 7 genannt ist :-(

**Comment by denniserdmann** [comment]
Wir haben den PHP 8 Support ergänzt, da wir keine größeren Probleme vermuten. Danke @katgirl für die Unterstützung!
