### ISSUE TITLE
Fehler der mobilen Ansicht durch CSS-Klasse news-list?

### ISSUE THREAD

**Issue by ghost** [ErdmannFreunde/optimist-theme-bundle#7]
Hallo zusammen,

vor ein paar Wochen bin ich auf Contao und das Optimist Theme umgestiegen. Ich bin noch dabei ein paar Sachen zu lernen und für mich anzupassen, aber hier glaube ich einen Fehler gefunden zu haben. Falls das doch mit Absicht so sein soll, dann kann diese Melden natürlich ignoriert werden.

Ich bin noch absoluter Anfänger und hoffe die richtigen Fachbegriffe zu nutzen, falls nicht, tut es mit leid.

Es geht um die Ansicht der News-List und der CSS Klasse "news-list". In der Desktopansicht wird das Newsbild links angezeigt und rechts der Text. In der mobilen Ansicht soll das Bild ja dann nach oben wechseln und der Text nach unten. Das funktioniert soweit auch, doch wird das Bild, je nachdem wie lang der Teasertext ist, unterschiedlich groß angezeigt. Das Bild hat nicht die volle Breite. Das liegt wohl am Grid, dass durch die CSS Klasse "news-list" erstellt wird? Dadurch wandert das Bild immer in die erste Spalte, aber die erste Spalte wird komischerweise mal größer oder kleiner und das Grid nicht gleichmäßig aufgeteilt.

Ich hoffe das anhängen von den Bildern hat geklappt, ansonsten als Beispiel diese Übersicht: https://www.finaltestman.de/testbericht

Viele Grüße
Santo
1. Bild mobile Ansicht ohne CSS Klasse
2. Bild Desktopansicht
3. Bild mobile Ansicht mit CSS Klasse
4. Bild mobile Ansicht Grid Anzeige
![Testberichte_Mobileansicht_ohne news list CSS Klasse](https://user-images.githubusercontent.com/80194172/110234351-4ea93c80-7f2a-11eb-94b7-af8f41545b02.jpg)
![Testberichte_Desktopansicht](https://user-images.githubusercontent.com/80194172/110234352-4f41d300-7f2a-11eb-998b-c999bf4a2bff.jpg)
![Testberichte_Mobileansicht](https://user-images.githubusercontent.com/80194172/110234353-4fda6980-7f2a-11eb-966e-2698358d181f.jpg)
![Testberichte_Mobileansicht_mit Grid](https://user-images.githubusercontent.com/80194172/110234354-4fda6980-7f2a-11eb-93cb-64e18c2eb299.jpg)

**Comment by denniserdmann** [comment]
Moin @FinalTestMan,
vielen Dank für die ausführliche Fehlerbeschreibung. Kannst du mal folgendes testen. In https://github.com/ErdmannFreunde/optimist-theme-bundle/blob/master/skeleton/files/theme/scss/components/_news.scss#L74-L79

ersetzt du den Block durch folgendes:

```
@include media-query(screen-md) {
  #{headings()},
  .info,
  .ce_text,
  .more {
    @include make-col(6);
  }
}
```

Dadurch greift die Anweisung erst ab dem Medium-Viewport, wenn das Bild link und der Text rechts steht.

**Comment by ghost** [comment]
Hallo @denniserdmann,

danke für die schnelle Antwort. Ich habe den Lösungsvorschlag gerade ausprobiert.
Funktioniert alles! Vielen Dank!

Viele Grüße und noch einen schönen Abend
Santo
