### ISSUE TITLE
trumps helper.scss

### ISSUE THREAD

**Issue by tuxenberger** [ErdmannFreunde/optimist-theme-bundle#8]
Hi Dennis,

in der helper.scss ist in Zeile 49 bei der Formelberechnung ein "i" nach der {$i} reingerutsch:

    padding-top: calc(#{$i}i * var(--base-spacing-unit));

Da ich nicht weiß wie man das hier als pullrequest mit verbesserter Datei senden kann auf diesem Wege.

Viele Grüße, Marcel

**Comment by denniserdmann** [comment]
Vielen Dank, Marcel! 

Behoben in https://github.com/ErdmannFreunde/optimist-theme-bundle/releases/tag/1.1.7
